### ISSUE TITLE
 Allow selecting specific resources 

### ISSUE THREAD

**Issue by yonahd** [yonahd/kor#2]
In order to allow user to run the tool on a specific namespace 
Create -n flag which would apply to all resources that can be namespaced.

e.g. `kor cm,secret -n my-namespce`

**Comment by Yuni-sa** [comment]
@yonahd 
It appears that this issue has been ongoing for a while now. I can create a PR for it. Note that calling multiple subcommands directly from the root command instead of from a subcommand (such as "kubectl **get** ingress,deployment"), it can be tricky as the logic needs to be in the rootcmd function.

I think it would be better to call it from the root command like `kor cm, secret -n my-namespace`, so I will implement it that way.
